// 여행 스타일 매핑
const travelStyleMap = {
    adventure: { name: "모험형", emoji: "🏔️", color: "#f59e0b" },
    relaxation: { name: "휴양형", emoji: "🏖️", color: "#14b8a6" },
    culture: { name: "문화탐방형", emoji: "🏛️", color: "#8b5cf6" },
    foodie: { name: "미식형", emoji: "🍜", color: "#ec4899" },
    nature: { name: "자연형", emoji: "🌲", color: "#10b981" },
};

// ================================================
// 🎯 사용자 성향 기반 추천 여행지
// ================================================
const userTravelProfile = {
    personality: "adventure", // adventure, relaxation, culture, foodie, nature
    budget: "medium", // low, medium, high
    travelStyle: "액티비티 중심",
    preferences: ["자연", "모험", "사진촬영"],
};

const recommendedDestinationsData = [
    {
        id: "rec-1",
        name: "퀸즈타운",
        country: "뉴질랜드",
        emoji: "🏔️",
        description:
            "스릴 넘치는 액티비티와 절경을 동시에 즐길 수 있는 모험가의 천국",
        longDescription:
            "퀸즈타운은 번지점프의 발상지이자 전 세계 모험가들이 찾는 메카입니다. 스카이다이빙, 제트보트, 패러글라이딩 등 다양한 익스트림 스포츠를 즐길 수 있으며, 밀포드 사운드의 경이로운 자연 경관도 감상할 수 있습니다.",
        tags: ["번지점프", "스카이다이빙", "밀포드사운드"],
        matchScore: 98,
        matchReasons: [
            "모험 성향 완벽 매치",
            "액티비티 천국",
            "자연 경관 우수",
        ],
        rating: 4.9,
        reviewCount: "2,847개 리뷰",
        estimatedBudget: "150만원~",
        bestSeason: "12월~2월",
        activities: [
            "번지점프",
            "스카이다이빙",
            "제트보트",
            "하이킹",
            "패러글라이딩",
        ],
        image: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800",
        highlights: [
            { icon: "🪂", title: "스카이다이빙", desc: "15,000ft 높이에서" },
            { icon: "🚤", title: "제트보트", desc: "360도 스핀 체험" },
            { icon: "⛰️", title: "밀포드 사운드", desc: "세계 8대 절경" },
        ],
    },
    {
        id: "rec-2",
        name: "인터라켄",
        country: "스위스",
        emoji: "⛰️",
        description: "알프스의 심장부에서 즐기는 패러글라이딩과 융프라우 등반",
        longDescription:
            "융프라우, 몽크, 아이거로 둘러싸인 인터라켄은 유럽 최고의 모험 스포츠 중심지입니다. 패러글라이딩으로 알프스를 조망하고, 스카이다이빙, 캐녀닝 등 다양한 액티비티를 즐길 수 있습니다.",
        tags: ["패러글라이딩", "융프라우", "알프스"],
        matchScore: 95,
        matchReasons: [
            "산악 액티비티 풍부",
            "사진 명소 다수",
            "자연 경관 최고",
        ],
        rating: 4.8,
        reviewCount: "3,192개 리뷰",
        estimatedBudget: "200만원~",
        bestSeason: "6월~9월",
        activities: [
            "패러글라이딩",
            "하이킹",
            "캐녀닝",
            "스카이다이빙",
            "등산",
        ],
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
        highlights: [
            { icon: "🪂", title: "패러글라이딩", desc: "알프스 상공 비행" },
            { icon: "🚞", title: "융프라우 철도", desc: "유럽 최고봉 등반" },
            { icon: "❄️", title: "빙하 체험", desc: "알레치 빙하 투어" },
        ],
    },
    {
        id: "rec-3",
        name: "케언즈",
        country: "호주",
        emoji: "🤿",
        description: "그레이트 배리어 리프에서의 스쿠버다이빙과 열대우림 탐험",
        longDescription:
            "케언즈는 세계 최대 산호초 지대인 그레이트 배리어 리프의 관문입니다. 스쿠버다이빙, 스노클링으로 수중 세계를 탐험하고, 댄트리 열대우림에서 짚라인과 래프팅을 즐길 수 있습니다.",
        tags: ["다이빙", "열대우림", "스노클링"],
        matchScore: 92,
        matchReasons: ["수중 액티비티 최적", "이색 체험 가능", "자연 다양성"],
        rating: 4.7,
        reviewCount: "2,563개 리뷰",
        estimatedBudget: "180만원~",
        bestSeason: "5월~10월",
        activities: [
            "스쿠버다이빙",
            "스노클링",
            "짚라인",
            "래프팅",
            "열대우림 투어",
        ],
        image: "https://images.unsplash.com/photo-1587339113293-82f8f0fc18ff?w=800",
        highlights: [
            {
                icon: "🤿",
                title: "그레이트 배리어 리프",
                desc: "세계 최대 산호초",
            },
            { icon: "🌴", title: "댄트리 열대우림", desc: "1억 3천만년 역사" },
            {
                icon: "🦘",
                title: "야생동물 투어",
                desc: "코알라·캥거루 만나기",
            },
        ],
    },
    {
        id: "rec-4",
        name: "아이슬란드",
        country: "아이슬란드",
        emoji: "🌋",
        description:
            "빙하 하이킹, 오로라 관측, 화산 탐험이 가능한 대자연의 나라",
        longDescription:
            "아이슬란드는 불과 얼음의 땅으로 지구상에서 가장 독특한 자연 경관을 자랑합니다. 빙하 위를 걷고, 화산 분화구를 탐험하며, 밤하늘의 오로라를 감상하는 특별한 경험을 할 수 있습니다.",
        tags: ["빙하하이킹", "오로라", "온천"],
        matchScore: 90,
        matchReasons: [
            "독특한 자연 체험",
            "사진 촬영 최적지",
            "모험 코스 다양",
        ],
        rating: 4.9,
        reviewCount: "4,021개 리뷰",
        estimatedBudget: "250만원~",
        bestSeason: "9월~3월 (오로라)",
        activities: [
            "빙하 하이킹",
            "오로라 투어",
            "스노클링",
            "온천",
            "화산 탐험",
        ],
        image: "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=800",
        highlights: [
            { icon: "🌌", title: "오로라", desc: "노던라이트 관측" },
            { icon: "🧊", title: "빙하 동굴", desc: "푸른 얼음 세계" },
            { icon: "♨️", title: "블루라군", desc: "천연 온천 힐링" },
        ],
    },
];

// ================================================
// ✈️ 항공권 데이터 (총 12개)
// ================================================
const flightDealsData = [
    {
        id: "flight-tokyo-001",
        from: "인천",
        fromCode: "ICN",
        to: "도쿄",
        toCode: "NRT",
        airline: "대한항공",
        departureTime: "10:30",
        arrivalTime: "12:50",
        duration: "2박 3일",
        date: "2026-03-15",
        returnDate: "2026-03-18",
        startDate: "2026-03-15",
        endDate: "2026-03-18",
        originalPrice: 520000,
        currentPrice: 296000,
        price: 296000,
        discount: 43,
        image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
        class: "이코노미",
        seatClass: "이코노미",
        baggage: "23kg x 1",
        stops: "직항",
        airlineType: "직항",
        services: ["기내식 제공", "수하물 23kg", "좌석 선택"],
        outbound: {
            departTime: "10:30",
            arriveTime: "12:50",
            flightTime: "2시간 20분",
            date: "2026.03.15",
        },
        inbound: {
            departTime: "14:00",
            arriveTime: "16:20",
            flightTime: "2시간 20분",
            date: "2026.03.18",
        },
    },
    {
        id: "flight-paris-002",
        from: "인천",
        fromCode: "ICN",
        to: "파리",
        toCode: "CDG",
        airline: "에어프랑스",
        departureTime: "13:45",
        arrivalTime: "18:30",
        duration: "6박 7일",
        date: "2026-04-10",
        returnDate: "2026-04-17",
        startDate: "2026-04-10",
        endDate: "2026-04-17",
        originalPrice: 1250000,
        currentPrice: 750000,
        price: 750000,
        discount: 40,
        image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        class: "이코노미",
        seatClass: "이코노미",
        baggage: "23kg x 2",
        stops: "직항",
        airlineType: "직항",
        services: [
            "기내식 제공",
            "수하물 46kg",
            "좌석 선택",
            "기내 엔터테인먼트",
        ],
        outbound: {
            departTime: "13:45",
            arriveTime: "18:30",
            flightTime: "12시간 45분",
            date: "2026.04.10",
        },
        inbound: {
            departTime: "20:00",
            arriveTime: "15:30",
            flightTime: "11시간 30분",
            date: "2026.04.17",
        },
    },
    {
        id: "flight-bali-003",
        from: "인천",
        fromCode: "ICN",
        to: "발리",
        toCode: "DPS",
        airline: "가루다 인도네시아",
        departureTime: "09:00",
        arrivalTime: "15:30",
        duration: "4박 5일",
        date: "2026-05-20",
        returnDate: "2026-05-25",
        startDate: "2026-05-20",
        endDate: "2026-05-25",
        originalPrice: 680000,
        currentPrice: 408000,
        price: 408000,
        discount: 41,
        image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
        class: "이코노미",
        seatClass: "이코노미",
        baggage: "23kg x 1",
        stops: "직항",
        airlineType: "직항",
        services: ["기내식 제공", "수하물 23kg", "좌석 선택"],
        outbound: {
            departTime: "09:00",
            arriveTime: "15:30",
            flightTime: "7시간 30분",
            date: "2026.05.20",
        },
        inbound: {
            departTime: "16:30",
            arriveTime: "23:00",
            flightTime: "7시간 30분",
            date: "2026.05.25",
        },
    },
    {
        id: "flight-newyork-004",
        from: "인천",
        fromCode: "ICN",
        to: "뉴욕",
        toCode: "JFK",
        airline: "유나이티드 항공",
        departureTime: "16:00",
        arrivalTime: "16:45",
        duration: "6박 7일",
        date: "2026-06-01",
        returnDate: "2026-06-08",
        startDate: "2026-06-01",
        endDate: "2026-06-08",
        originalPrice: 1800000,
        currentPrice: 990000,
        price: 990000,
        discount: 42,
        image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800",
        class: "이코노미",
        seatClass: "이코노미",
        baggage: "23kg x 2",
        stops: "직항",
        airlineType: "직항",
        services: ["기내식 제공", "수하물 46kg", "좌석 선택", "기내 와이파이"],
        outbound: {
            departTime: "16:00",
            arriveTime: "16:45",
            flightTime: "13시간 45분",
            date: "2026.06.01",
        },
        inbound: {
            departTime: "12:00",
            arriveTime: "16:30",
            flightTime: "14시간 30분",
            date: "2026.06.08",
        },
    },
    {
        id: "flight-osaka-005",
        from: "인천",
        fromCode: "ICN",
        to: "오사카",
        toCode: "KIX",
        airline: "ANA",
        departureTime: "08:15",
        arrivalTime: "10:20",
        duration: "3박 4일",
        date: "2026-03-22",
        returnDate: "2026-03-26",
        startDate: "2026-03-22",
        endDate: "2026-03-26",
        originalPrice: 450000,
        currentPrice: 279000,
        price: 279000,
        discount: 38,
        image: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800",
        class: "이코노미",
        seatClass: "이코노미",
        baggage: "23kg x 1",
        stops: "직항",
        airlineType: "직항",
        services: ["기내식 제공", "수하물 23kg", "좌석 선택"],
        outbound: {
            departTime: "08:15",
            arriveTime: "10:20",
            flightTime: "2시간 5분",
            date: "2026.03.22",
        },
        inbound: {
            departTime: "12:00",
            arriveTime: "14:05",
            flightTime: "2시간 5분",
            date: "2026.03.26",
        },
    },
    {
        id: "flight-london-006",
        from: "인천",
        fromCode: "ICN",
        to: "런던",
        toCode: "LHR",
        airline: "영국항공",
        departureTime: "12:30",
        arrivalTime: "17:15",
        duration: "6박 7일",
        date: "2026-07-15",
        returnDate: "2026-07-22",
        startDate: "2026-07-15",
        endDate: "2026-07-22",
        originalPrice: 1500000,
        currentPrice: 825000,
        price: 825000,
        discount: 40,
        image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800",
        class: "이코노미",
        seatClass: "이코노미",
        baggage: "23kg x 2",
        stops: "직항",
        airlineType: "직항",
        services: [
            "기내식 제공",
            "수하물 46kg",
            "좌석 선택",
            "기내 엔터테인먼트",
        ],
        outbound: {
            departTime: "12:30",
            arriveTime: "17:15",
            flightTime: "12시간 45분",
            date: "2026.07.15",
        },
        inbound: {
            departTime: "19:00",
            arriveTime: "14:30",
            flightTime: "11시간 30분",
            date: "2026.07.22",
        },
    },
    {
        id: "flight-singapore-007",
        from: "인천",
        fromCode: "ICN",
        to: "싱가포르",
        toCode: "SIN",
        airline: "싱가포르항공",
        departureTime: "11:00",
        arrivalTime: "17:00",
        duration: "4박 5일",
        date: "2026-04-05",
        returnDate: "2026-04-10",
        startDate: "2026-04-05",
        endDate: "2026-04-10",
        originalPrice: 720000,
        currentPrice: 432000,
        price: 432000,
        discount: 39,
        image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800",
        class: "이코노미",
        seatClass: "이코노미",
        baggage: "30kg x 1",
        stops: "직항",
        airlineType: "직항",
        services: [
            "기내식 제공",
            "수하물 30kg",
            "좌석 선택",
            "기내 엔터테인먼트",
        ],
        outbound: {
            departTime: "11:00",
            arriveTime: "17:00",
            flightTime: "6시간",
            date: "2026.04.05",
        },
        inbound: {
            departTime: "23:00",
            arriveTime: "06:30",
            flightTime: "6시간 30분",
            date: "2026.04.10",
        },
    },
    {
        id: "flight-dubai-008",
        from: "인천",
        fromCode: "ICN",
        to: "두바이",
        toCode: "DXB",
        airline: "에미레이트 항공",
        departureTime: "22:30",
        arrivalTime: "04:30",
        duration: "5박 6일",
        date: "2026-05-01",
        returnDate: "2026-05-07",
        startDate: "2026-05-01",
        endDate: "2026-05-07",
        originalPrice: 1600000,
        currentPrice: 880000,
        price: 880000,
        discount: 43,
        image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
        class: "이코노미",
        seatClass: "이코노미",
        baggage: "30kg x 2",
        stops: "직항",
        airlineType: "직항",
        services: [
            "기내식 제공",
            "수하물 60kg",
            "좌석 선택",
            "기내 엔터테인먼트",
            "기내 와이파이",
        ],
        outbound: {
            departTime: "22:30",
            arriveTime: "04:30",
            flightTime: "9시간",
            date: "2026.05.01",
        },
        inbound: {
            departTime: "02:00",
            arriveTime: "15:00",
            flightTime: "8시간",
            date: "2026.05.07",
        },
    },
    {
        id: "flight-barcelona-009",
        from: "인천",
        fromCode: "ICN",
        to: "바르셀로나",
        toCode: "BCN",
        airline: "이베리아 항공",
        departureTime: "14:00",
        arrivalTime: "20:30",
        duration: "7박 8일",
        date: "2026-06-10",
        returnDate: "2026-06-18",
        startDate: "2026-06-10",
        endDate: "2026-06-18",
        originalPrice: 1700000,
        currentPrice: 935000,
        price: 935000,
        discount: 42,
        image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800",
        class: "이코노미",
        seatClass: "이코노미",
        baggage: "23kg x 2",
        stops: "직항",
        airlineType: "직항",
        services: [
            "기내식 제공",
            "수하물 46kg",
            "좌석 선택",
            "기내 엔터테인먼트",
        ],
        outbound: {
            departTime: "14:00",
            arriveTime: "20:30",
            flightTime: "13시간 30분",
            date: "2026.06.10",
        },
        inbound: {
            departTime: "22:00",
            arriveTime: "17:00",
            flightTime: "12시간",
            date: "2026.06.18",
        },
    },
    {
        id: "flight-sydney-010",
        from: "인천",
        fromCode: "ICN",
        to: "시드니",
        toCode: "SYD",
        airline: "콴타스 항공",
        departureTime: "19:00",
        arrivalTime: "07:30",
        duration: "6박 7일",
        date: "2026-07-01",
        returnDate: "2026-07-08",
        startDate: "2026-07-01",
        endDate: "2026-07-08",
        originalPrice: 1900000,
        currentPrice: 1045000,
        price: 1045000,
        discount: 38,
        image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800",
        class: "이코노미",
        seatClass: "이코노미",
        baggage: "30kg x 2",
        stops: "직항",
        airlineType: "직항",
        services: [
            "기내식 제공",
            "수하물 60kg",
            "좌석 선택",
            "기내 엔터테인먼트",
        ],
        outbound: {
            departTime: "19:00",
            arriveTime: "07:30",
            flightTime: "10시간 30분",
            date: "2026.07.01",
        },
        inbound: {
            departTime: "10:00",
            arriveTime: "18:00",
            flightTime: "10시간",
            date: "2026.07.08",
        },
    },
    {
        id: "flight-rome-011",
        from: "인천",
        fromCode: "ICN",
        to: "로마",
        toCode: "FCO",
        airline: "알이탈리아",
        departureTime: "15:30",
        arrivalTime: "21:00",
        duration: "6박 7일",
        date: "2026-05-15",
        returnDate: "2026-05-22",
        startDate: "2026-05-15",
        endDate: "2026-05-22",
        originalPrice: 1650000,
        currentPrice: 907500,
        price: 907500,
        discount: 39,
        image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
        class: "이코노미",
        seatClass: "이코노미",
        baggage: "23kg x 2",
        stops: "직항",
        airlineType: "직항",
        services: [
            "기내식 제공",
            "수하물 46kg",
            "좌석 선택",
            "기내 엔터테인먼트",
        ],
        outbound: {
            departTime: "15:30",
            arriveTime: "21:00",
            flightTime: "12시간 30분",
            date: "2026.05.15",
        },
        inbound: {
            departTime: "23:00",
            arriveTime: "17:00",
            flightTime: "11시간",
            date: "2026.05.22",
        },
    },
    {
        id: "flight-bangkok-012",
        from: "인천",
        fromCode: "ICN",
        to: "방콕",
        toCode: "BKK",
        airline: "타이항공",
        departureTime: "10:00",
        arrivalTime: "14:00",
        duration: "4박 5일",
        date: "2026-04-20",
        returnDate: "2026-04-25",
        startDate: "2026-04-20",
        endDate: "2026-04-25",
        originalPrice: 550000,
        currentPrice: 330000,
        price: 330000,
        discount: 40,
        image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800",
        class: "이코노미",
        seatClass: "이코노미",
        baggage: "30kg x 1",
        stops: "직항",
        airlineType: "직항",
        services: ["기내식 제공", "수하물 30kg", "좌석 선택"],
        outbound: {
            departTime: "10:00",
            arriveTime: "14:00",
            flightTime: "5시간",
            date: "2026.04.20",
        },
        inbound: {
            departTime: "15:30",
            arriveTime: "22:30",
            flightTime: "5시간",
            date: "2026.04.25",
        },
    },
];

// ================================================
// 🔥 인기 여행지 데이터 (총 20개)
// ================================================
const popularDestinationsData = [
    {
        rank: 1,
        city: "도쿄",
        name: "도쿄",
        country: "일본",
        emoji: "🗼",
        description: "전통과 현대가 공존하는 매력적인 도시",
        tags: ["쇼핑천국", "미식여행", "문화체험"],
        rating: 4.8,
        visitors: "320만명",
        trend: "급상승 🔥",
        rankChange: 2,
        image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    },
    {
        rank: 2,
        city: "파리",
        name: "파리",
        country: "프랑스",
        emoji: "🗼",
        description: "낭만의 도시, 예술과 문화의 중심지",
        tags: ["낭만여행", "미술관", "맛집투어"],
        rating: 4.9,
        visitors: "280만명",
        trend: "",
        rankChange: 1,
        image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
    },
    {
        rank: 3,
        city: "발리",
        name: "발리",
        country: "인도네시아",
        emoji: "🏝️",
        description: "천국의 섬, 힐링과 휴식의 완벽한 조화",
        tags: ["휴양지", "비치", "스파"],
        rating: 4.7,
        visitors: "250만명",
        trend: "급상승 🔥",
        rankChange: 3,
        image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
    },
    {
        rank: 4,
        city: "뉴욕",
        name: "뉴욕",
        country: "미국",
        emoji: "🗽",
        description: "잠들지 않는 도시, 꿈과 희망의 상징",
        tags: ["도시여행", "쇼핑", "뮤지컬"],
        rating: 4.6,
        visitors: "230만명",
        trend: "",
        rankChange: 0,
        image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800",
    },
    {
        rank: 5,
        city: "오사카",
        name: "오사카",
        country: "일본",
        emoji: "🏯",
        description: "일본의 부엌, 먹방 여행의 성지",
        tags: ["미식투어", "쇼핑", "야경"],
        rating: 4.5,
        visitors: "210만명",
        trend: "",
        rankChange: 1,
        image: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800",
    },
    {
        rank: 6,
        city: "런던",
        name: "런던",
        country: "영국",
        emoji: "🏛️",
        description: "역사와 전통의 도시, 왕실의 품격",
        tags: ["역사탐방", "박물관", "쇼핑"],
        rating: 4.6,
        visitors: "195만명",
        trend: "",
        rankChange: -1,
        image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800",
    },
    {
        rank: 7,
        city: "싱가포르",
        name: "싱가포르",
        country: "싱가포르",
        emoji: "🦁",
        description: "미래 도시, 깨끗하고 안전한 여행지",
        tags: ["도시관광", "미식", "쇼핑"],
        rating: 4.7,
        visitors: "180만명",
        trend: "",
        rankChange: 2,
        image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800",
    },
    {
        rank: 8,
        city: "두바이",
        name: "두바이",
        country: "UAE",
        emoji: "🏙️",
        description: "사막 위의 기적, 초호화 여행지",
        tags: ["럭셔리", "쇼핑", "사막투어"],
        rating: 4.6,
        visitors: "175만명",
        trend: "급상승 🔥",
        rankChange: 4,
        image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    },
    {
        rank: 9,
        city: "바르셀로나",
        name: "바르셀로나",
        country: "스페인",
        emoji: "🏛️",
        description: "가우디의 도시, 예술과 열정이 살아있는 곳",
        tags: ["건축", "비치", "예술"],
        rating: 4.8,
        visitors: "170만명",
        trend: "",
        rankChange: 1,
        image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800",
    },
    {
        rank: 10,
        city: "시드니",
        name: "시드니",
        country: "호주",
        emoji: "🎭",
        description: "자연과 도시의 완벽한 조화",
        tags: ["해변", "도시", "자연"],
        rating: 4.5,
        visitors: "165만명",
        trend: "",
        rankChange: 0,
        image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800",
    },
    {
        rank: 11,
        city: "로마",
        name: "로마",
        country: "이탈리아",
        emoji: "🏛️",
        description: "영원한 도시, 역사의 보고",
        tags: ["역사", "문화", "음식"],
        rating: 4.7,
        visitors: "160만명",
        trend: "",
        rankChange: -2,
        image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
    },
    {
        rank: 12,
        city: "방콕",
        name: "방콕",
        country: "태국",
        emoji: "🛕",
        description: "미소의 나라, 황금빛 사원과 맛있는 음식",
        tags: ["사원", "쇼핑", "마사지"],
        rating: 4.4,
        visitors: "155만명",
        trend: "",
        rankChange: 2,
        image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800",
    },
    {
        rank: 13,
        city: "홍콩",
        name: "홍콩",
        country: "중국",
        emoji: "🌃",
        description: "동양과 서양이 만나는 곳",
        tags: ["야경", "쇼핑", "딤섬"],
        rating: 4.3,
        visitors: "150만명",
        trend: "",
        rankChange: -1,
        image: "https://media.triple.guide/triple-cms/c_limit,f_auto,h_1024,w_1024/a62549a3-f9b8-49c2-a4af-d79e19d093a5.jpeg",
    },
    {
        rank: 14,
        city: "프라하",
        name: "프라하",
        country: "체코",
        emoji: "🏰",
        description: "동화 같은 도시, 건축의 보석",
        tags: ["건축", "야경", "맥주"],
        rating: 4.6,
        visitors: "145만명",
        trend: "급상승 🔥",
        rankChange: 5,
        image: "https://images.unsplash.com/photo-1541849546-216549ae216d?w=800",
    },
    {
        rank: 15,
        city: "상하이",
        name: "상하이",
        country: "중국",
        emoji: "🌆",
        description: "과거와 현재가 공존하는 초현대 도시",
        tags: ["야경", "쇼핑", "중식"],
        rating: 4.4,
        visitors: "140만명",
        trend: "",
        rankChange: 0,
        image: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=800",
    },
    {
        rank: 16,
        city: "이스탄불",
        name: "이스탄불",
        country: "터키",
        emoji: "🕌",
        description: "동서양의 교차로, 신비로운 매력",
        tags: ["역사", "문화", "야시장"],
        rating: 4.5,
        visitors: "135만명",
        trend: "",
        rankChange: 3,
        image: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800",
    },
    {
        rank: 17,
        city: "암스테르담",
        name: "암스테르담",
        country: "네덜란드",
        emoji: "🚲",
        description: "운하의 도시, 자전거 천국",
        tags: ["운하", "미술관", "자전거"],
        rating: 4.5,
        visitors: "130만명",
        trend: "",
        rankChange: -2,
        image: "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=800",
    },
    {
        rank: 18,
        city: "베를린",
        name: "베를린",
        country: "독일",
        emoji: "🚪",
        description: "역사의 흔적과 예술이 살아있는 도시",
        tags: ["역사", "예술", "클럽"],
        rating: 4.3,
        visitors: "125만명",
        trend: "",
        rankChange: 1,
        image: "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800",
    },
    {
        rank: 19,
        city: "비엔나",
        name: "비엔나",
        country: "오스트리아",
        emoji: "🎻",
        description: "음악의 도시, 우아한 제국의 수도",
        tags: ["음악", "궁전", "카페"],
        rating: 4.7,
        visitors: "120만명",
        trend: "급상승 🔥",
        rankChange: 6,
        image: "https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800",
    },
    {
        rank: 20,
        city: "부다페스트",
        name: "부다페스트",
        country: "헝가리",
        emoji: "🏰",
        description: "도나우강의 진주, 로맨틱한 야경",
        tags: ["야경", "온천", "와인"],
        rating: 4.6,
        visitors: "115만명",
        trend: "",
        rankChange: 2,
        image: "https://images.unsplash.com/photo-1541849546-216549ae216d?w=800",
    },
];

// ================================================
// 📅 도시별 추천 일정 데이터
// ================================================
const citySchedulesData = {
    도쿄: {
        "3일": [
            {
                day: 1,
                title: "도쿄 도착 & 아사쿠사",
                activities: [
                    "센소지 절 방문",
                    "나카미세 거리 쇼핑",
                    "스카이트리 야경",
                ],
            },
            {
                day: 2,
                title: "시부야 & 하라주쿠",
                activities: [
                    "시부야 스크램블 교차로",
                    "메이지 신궁",
                    "하라주쿠 쇼핑",
                    "원두코마치 거리",
                ],
            },
            {
                day: 3,
                title: "츠키지 & 귀국",
                activities: ["츠키지 시장 아침 식사", "긴자 쇼핑", "공항 이동"],
            },
        ],
        "5일": [
            {
                day: 1,
                title: "도쿄 도착",
                activities: ["호텔 체크인", "신주쿠 야경", "이자카야 체험"],
            },
            {
                day: 2,
                title: "아사쿠사 & 우에노",
                activities: ["센소지 절", "우에노 공원", "아메요코 쇼핑"],
            },
            {
                day: 3,
                title: "시부야 & 하라주쿠",
                activities: [
                    "시부야 109",
                    "메이지 신궁",
                    "오모테산도",
                    "타케시타 거리",
                ],
            },
            {
                day: 4,
                title: "도쿄 디즈니랜드",
                activities: ["하루종일 디즈니랜드 즐기기"],
            },
            {
                day: 5,
                title: "츠키지 & 귀국",
                activities: ["츠키지 시장", "긴자 쇼핑", "공항 출발"],
            },
        ],
    },
    파리: {
        "7일": [
            {
                day: 1,
                title: "파리 도착",
                activities: [
                    "호텔 체크인",
                    "몽마르트르 언덕",
                    "사크레쾨르 성당",
                ],
            },
            {
                day: 2,
                title: "루브르 & 샹젤리제",
                activities: [
                    "루브르 박물관",
                    "튈르리 정원",
                    "샹젤리제 거리",
                    "개선문",
                ],
            },
            {
                day: 3,
                title: "에펠탑 & 센강",
                activities: ["에펠탑 등반", "트로카데로 광장", "센강 유람선"],
            },
            {
                day: 4,
                title: "베르사유 궁전",
                activities: ["베르사유 궁전 투어", "정원 산책"],
            },
            {
                day: 5,
                title: "마레 지구 & 노트르담",
                activities: [
                    "노트르담 대성당",
                    "마레 지구 카페",
                    "빅토르 위고 생가",
                ],
            },
            {
                day: 6,
                title: "오르세 미술관",
                activities: [
                    "오르세 미술관",
                    "생제르맹 거리",
                    "카페 드 플로르",
                ],
            },
            {
                day: 7,
                title: "쇼핑 & 귀국",
                activities: ["갤러리 라파예트", "프랑탕 백화점", "공항 출발"],
            },
        ],
    },
    발리: {
        "5일": [
            {
                day: 1,
                title: "발리 도��",
                activities: ["호텔 체크인", "쿠타 비치 석양", "비치 클럽"],
            },
            {
                day: 2,
                title: "우붓 투어",
                activities: [
                    "테갈랄랑 라이스 테라스",
                    "우붓 원숭이 숲",
                    "우붓 왕궁",
                ],
            },
            {
                day: 3,
                title: "탄중 베노아 워터스포츠",
                activities: ["바나나 보트", "플라이 피시", "스노클링"],
            },
            {
                day: 4,
                title: "울루와투 사원",
                activities: [
                    "울루와투 사원",
                    "케차 댄스 공연",
                    "징바란 씨푸드",
                ],
            },
            {
                day: 5,
                title: "쇼핑 & 귀국",
                activities: ["스미냑 쇼핑", "스파", "공항 출발"],
            },
        ],
    },
    뉴욕: {
        "7일": [
            {
                day: 1,
                title: "뉴욕 도착",
                activities: ["타임스퀘어", "브로드웨이 뮤지컬"],
            },
            {
                day: 2,
                title: "맨해튼 랜드마크",
                activities: ["자유의 여신상", "월 스트리트", "브루클린 브릿지"],
            },
            {
                day: 3,
                title: "센트럴 파크 & 박물관",
                activities: [
                    "센트럴 파크",
                    "메트로폴리탄 미술관",
                    "5번가 쇼핑",
                ],
            },
            {
                day: 4,
                title: "엠파이어 스테이트 빌딩",
                activities: ["엠파이어 스테이트 전망대", "록펠러 센터"],
            },
            {
                day: 5,
                title: "브루클린 탐방",
                activities: ["브루클린 덤보", "윌리엄스버그", "로컬 카페"],
            },
            {
                day: 6,
                title: "뮤지엄 투어",
                activities: ["자연사 박물관", "구겐하임 미술관"],
            },
            {
                day: 7,
                title: "쇼핑 & 귀국",
                activities: ["소호 쇼핑", "첼시 마켓", "공항 출발"],
            },
        ],
    },
    오사카: {
        "3일": [
            {
                day: 1,
                title: "오사카 도착",
                activities: ["도톤보리", "난바", "타코야키 맛집 투어"],
            },
            {
                day: 2,
                title: "오사카성 & 우메다",
                activities: ["오사카성", "우메다 스카이빌딩", "쿠로몬 시장"],
            },
            {
                day: 3,
                title: "유니버설 스튜디오",
                activities: ["유니버설 스튜디오 재팬 하루 즐기기"],
            },
        ],
    },
    런던: {
        "7일": [
            {
                day: 1,
                title: "런던 도착",
                activities: ["빅벤", "런던아이", "템즈강 산책"],
            },
            {
                day: 2,
                title: "대영박물관 & 코벤트 가든",
                activities: ["대영박물관", "코벤트 가든", "뮤지컬 관람"],
            },
            {
                day: 3,
                title: "버킹엄 궁전",
                activities: ["버킹엄 궁전 근위병 교대식", "세인트 제임스 공원"],
            },
            {
                day: 4,
                title: "타워 브릿지 & 타워 오브 런던",
                activities: ["타워 브릿지", "타워 오브 런던", "보로우 마켓"],
            },
            {
                day: 5,
                title: "캠든 타운",
                activities: ["캠든 마켓", "리젠트 파크", "셜록 홈즈 박물관"],
            },
            {
                day: 6,
                title: "옥스포드 당일치기",
                activities: ["옥스포드 대학 투어", "크라이스트 처치"],
            },
            {
                day: 7,
                title: "쇼핑 & 귀국",
                activities: ["옥스포드 스트리트", "해러즈 백화점", "공항 출발"],
            },
        ],
    },
    싱가포르: {
        "7일": [
            {
                day: 1,
                title: "싱가포르 도착",
                activities: ["마리나 베이 샌즈", "머라이언 파크", "클락 키"],
            },
            {
                day: 2,
                title: "가든스 바이 더 베이",
                activities: [
                    "슈퍼트리 그로브",
                    "플라워 돔",
                    "클라우드 포레스트",
                ],
            },
            {
                day: 3,
                title: "센토사",
                activities: [
                    "유니버설 스튜디오",
                    "S.E.A 아쿠아리움",
                    "케이블카",
                ],
            },
            {
                day: 4,
                title: "리틀 인디아 & 차이나타운",
                activities: ["리틀 인디아", "차이나타운", "호커센터 투어"],
            },
            {
                day: 5,
                title: "오차드 로드",
                activities: ["오차드 로드 쇼핑", "ION 스카이", "카페 투어"],
            },
            {
                day: 6,
                title: "동물원 & 나이트 사파리",
                activities: ["싱가포르 동물원", "나이트 사파리"],
            },
            {
                day: 7,
                title: "주롱 새공원 & 귀국",
                activities: ["주롱 새공원", "마지막 쇼핑", "공항 출발"],
            },
        ],
    },
    두바이: {
        "9일": [
            {
                day: 1,
                title: "두바이 도착",
                activities: ["호텔 체크인", "두바이 몰", "두바이 분수쇼"],
            },
            {
                day: 2,
                title: "부르즈 칼리파",
                activities: [
                    "부르즈 칼리파 전망대",
                    "스카이 라운지",
                    "수크 알 바하르",
                ],
            },
            {
                day: 3,
                title: "사막 사파리",
                activities: ["사막 드라이브", "낙타 체험", "베두인 캠프 디너"],
            },
            {
                day: 4,
                title: "팜 주메이라",
                activities: ["아틀란티스 더 팜", "워터파크", "아쿠아벤처"],
            },
            {
                day: 5,
                title: "두바이 마리나",
                activities: ["두바이 마리나 산책", "크루즈", "JBR 비치"],
            },
            {
                day: 6,
                title: "골드 수크 & 올드 두바이",
                activities: ["골드 수크", "스파이스 수크", "압토그라 크루즈"],
            },
            {
                day: 7,
                title: "부르즈 알 아랍",
                activities: [
                    "부르즈 알 아랍 애프터눈 티",
                    "주메이라 비치",
                    "소호 가든",
                ],
            },
            {
                day: 8,
                title: "쇼핑 & 여유",
                activities: ["몰 오브 에미리트", "스키 두바이", "라스트 쇼핑"],
            },
            { day: 9, title: "귀국", activities: ["마지막 쇼핑", "공항 출발"] },
        ],
    },
    바르셀로나: {
        "10일": [
            {
                day: 1,
                title: "바르셀로나 도착",
                activities: ["호텔 체크인", "람블라스 거리", "보케리아 시장"],
            },
            {
                day: 2,
                title: "사그라다 파밀리아",
                activities: [
                    "사그라다 파밀리아 투어",
                    "산 파우 병원",
                    "카사 바트요",
                ],
            },
            {
                day: 3,
                title: "구엘 공원",
                activities: ["구엘 공원", "그라시아 거리", "카사 밀라"],
            },
            {
                day: 4,
                title: "고딕 지구",
                activities: [
                    "고딕 지구 산책",
                    "바르셀로나 대성당",
                    "피카소 박물관",
                ],
            },
            {
                day: 5,
                title: "몬주익",
                activities: ["몬주익 언덕", "카탈루냐 미술관", "마술 분수 쇼"],
            },
            {
                day: 6,
                title: "바르셀로네타",
                activities: [
                    "바르셀로네타 해변",
                    "해산물 레스토랑",
                    "올림픽 항구",
                ],
            },
            {
                day: 7,
                title: "몬세라트 당일치기",
                activities: ["몬세라트 수도원", "등산", "블랙 마돈나"],
            },
            {
                day: 8,
                title: "캄프 누",
                activities: ["캄프 누 스타디움 투어", "FC 바르셀로나 박물관"],
            },
            {
                day: 9,
                title: "쇼핑 & 여유",
                activities: ["엘 꼬르떼 잉글레스", "패션 거리", "카페 투어"],
            },
            {
                day: 10,
                title: "귀국",
                activities: ["라스트 쇼핑", "공항 출발"],
            },
        ],
    },
    시드니: {
        "12일": [
            {
                day: 1,
                title: "시드니 도착",
                activities: ["호텔 체크인", "서큘러 키", "록스 지구"],
            },
            {
                day: 2,
                title: "오페라 하우스 & 하버 브릿지",
                activities: [
                    "오페라 하우스 투어",
                    "하버 브릿지 산책",
                    "맥퀘리 거리",
                ],
            },
            {
                day: 3,
                title: "본다이 비치",
                activities: [
                    "본다이 비치",
                    "본다이 to 쿠지 해안 산책",
                    "서핑 레슨",
                ],
            },
            {
                day: 4,
                title: "달링 하버",
                activities: [
                    "달링 하버",
                    "씨 라이프 아쿠아리움",
                    "와일드 라이프 시드니",
                ],
            },
            {
                day: 5,
                title: "블루 마운틴 당일치기",
                activities: ["블루 마운틴", "쓰리 시스터즈", "시닉 월드"],
            },
            {
                day: 6,
                title: "타롱가 동물원",
                activities: ["타롱가 동물원", "페리 타기", "코알라 체험"],
            },
            {
                day: 7,
                title: "맨리",
                activities: ["맨리 비치", "페리 타기", "해안 산책"],
            },
            {
                day: 8,
                title: "하버 크루즈",
                activities: ["하버 디너 크루즈", "와트슨스 베이"],
            },
            {
                day: 9,
                title: "헌터 밸리 와이너리",
                activities: ["와이너리 투어", "와인 시음", "치즈 농장"],
            },
            {
                day: 10,
                title: "QVB & 쇼핑",
                activities: ["퀸 빅토리아 빌딩", "피트 스트리트 몰", "쇼핑"],
            },
            {
                day: 11,
                title: "여유 & 라스트 쇼핑",
                activities: ["더 록스 마켓", "카페 투어", "선물 쇼핑"],
            },
            { day: 12, title: "귀국", activities: ["공항 출발"] },
        ],
    },
    로마: {
        "10일": [
            {
                day: 1,
                title: "로마 도착",
                activities: ["호텔 체크인", "트레비 분수", "스페인 광장"],
            },
            {
                day: 2,
                title: "콜로세움",
                activities: ["콜로세움 투어", "포로 로마노", "팔라티노 언덕"],
            },
            {
                day: 3,
                title: "바티칸 시국",
                activities: [
                    "바티칸 박물관",
                    "시스티나 성당",
                    "성 베드로 대성당",
                ],
            },
            {
                day: 4,
                title: "판테온 & 나보나 광장",
                activities: ["판테온", "나보나 광장", "캄포 데 피오리"],
            },
            {
                day: 5,
                title: "트라스테베레",
                activities: [
                    "트라스테베레 지구",
                    "산타 마리아 성당",
                    "현지 레스토랑",
                ],
            },
            {
                day: 6,
                title: "보르게제 미술관",
                activities: ["보르게제 미술관", "보르게제 공원", "스페인 계단"],
            },
            {
                day: 7,
                title: "베네치아 광장",
                activities: [
                    "베네치아 광장",
                    "빅토리오 에마누엘레 2세 기념관",
                    "카피톨리노 박물관",
                ],
            },
            {
                day: 8,
                title: "폼페이 & 나폴리 당일치기",
                activities: ["폼페이 유적지", "나폴리 피자", "베수비오 산"],
            },
            {
                day: 9,
                title: "쇼핑 & 여유",
                activities: [
                    "비아 델 꼬르소",
                    "디자이너 아울렛",
                    "젤라또 투어",
                ],
            },
            {
                day: 10,
                title: "귀국",
                activities: ["라스트 쇼핑", "공항 출발"],
            },
        ],
    },
    방콕: {
        "6일": [
            {
                day: 1,
                title: "방콕 도착",
                activities: ["호텔 체크인", "카오산 로드", "왓 아룬 야경"],
            },
            {
                day: 2,
                title: "왕궁 & 왓 포",
                activities: ["왕궁 투어", "왓 포 와불", "타이 마사지"],
            },
            {
                day: 3,
                title: "수상시장",
                activities: [
                    "담넌 사두억 수상시장",
                    "메클롱 기차시장",
                    "보트 투어",
                ],
            },
            {
                day: 4,
                title: "아유타야 당일치기",
                activities: ["아유타야 유적지", "사원 투어", "코끼리 체험"],
            },
            {
                day: 5,
                title: "쇼핑 & 스파",
                activities: ["시암 파라곤", "차투착 시장", "타이 스파"],
            },
            {
                day: 6,
                title: "마지막 쇼핑 & 귀국",
                activities: ["터미널21", "라스트 쇼핑", "공항 출발"],
            },
        ],
    },
};

// ================================================
// 🌍 도시별 여행 정보 데이터
// ================================================
const cityTravelInfoData = {
    도쿄: {
        bestSeason: "봄(3-5월), 가을(9-11월)",
        weather: "온대기후, 여름 덥고 습함",
        currency: "일본 엔(JPY)",
        language: "일본어",
        timezone: "GMT+9",
        attractions: [
            {
                name: "센소지 절",
                emoji: "⛩️",
                description: "도쿄에서 가장 오래된 사찰",
            },
            {
                name: "스카이트리",
                emoji: "🗼",
                description: "높이 634m의 전망대",
            },
            {
                name: "시부야 스크램블",
                emoji: "🚶",
                description: "세계에서 가장 바쁜 교차로",
            },
            {
                name: "메이지 신궁",
                emoji: "🌳",
                description: "도심 속 평화로운 신사",
            },
        ],
        restaurants: [
            { name: "스시 다이", emoji: "🍣", type: "스시", price: "¥¥¥" },
            { name: "이치란 라멘", emoji: "🍜", type: "라멘", price: "¥" },
            {
                name: "츠키지 스시세이",
                emoji: "🐟",
                type: "해산물",
                price: "¥¥",
            },
        ],
        hotels: [
            { name: "파크 하얏트 도쿄", rating: "⭐⭐⭐⭐⭐", area: "신주쿠" },
            {
                name: "도쿄 스테이션 호텔",
                rating: "⭐⭐⭐⭐",
                area: "마루노우치",
            },
        ],
        tips: [
            "💳 교통카드(Suica/Pasmo) 필수",
            "🚇 지하철 1일권 추천",
            "🎌 기본 일본어 인사말 익히기",
            "🗓️ 주말/공휴일 혼잡 주의",
        ],
    },
    파리: {
        bestSeason: "봄(4-6월), 가을(9-10월)",
        weather: "서안해양성기후, 겨울 온화",
        currency: "유로(EUR)",
        language: "프랑스어",
        timezone: "GMT+1",
        attractions: [
            { name: "에펠탑", emoji: "🗼", description: "파리의 상징" },
            {
                name: "루브르 박물관",
                emoji: "🖼️",
                description: "세계 3대 박물관",
            },
            {
                name: "개선문",
                emoji: "🏛️",
                description: "나폴레옹 승전 기념비",
            },
            {
                name: "노트르담 대성당",
                emoji: "⛪",
                description: "고딕 건축의 걸작",
            },
        ],
        restaurants: [
            {
                name: "르 쥘 베른",
                emoji: "🍽️",
                type: "프랑스 요리",
                price: "€€€€",
            },
            { name: "라뒤레", emoji: "🥐", type: "마카롱", price: "€€" },
            { name: "셰즈 라미", emoji: "🥖", type: "비스트로", price: "€€" },
        ],
        hotels: [
            { name: "리츠 파리", rating: "⭐⭐⭐⭐⭐", area: "방돔 광장" },
            { name: "르 마레 호텔", rating: "⭐⭐⭐⭐", area: "마레 지구" },
        ],
        tips: [
            "💳 뮤지엄 패스 구매 추천",
            "🚇 메트로 카르네(10장) 구매",
            "🥖 현지 베이커리 방문 필수",
            "👋 기본 프랑스어 인사 필수",
        ],
    },
    발리: {
        bestSeason: "건기(4-10월)",
        weather: "열대기후, 연중 고온다습",
        currency: "인도네시아 루피아(IDR)",
        language: "인도네시아어, 영어",
        timezone: "GMT+8",
        attractions: [
            {
                name: "우붓 라이스 테라스",
                emoji: "🌾",
                description: "계단식 논 풍경",
            },
            {
                name: "탄중 베노아",
                emoji: "🏄",
                description: "워터스포츠 천국",
            },
            {
                name: "울루와투 사원",
                emoji: "🏯",
                description: "절벽 위 힌두 사원",
            },
            {
                name: "몽키 포레스트",
                emoji: "🐒",
                description: "원숭이 보호구역",
            },
        ],
        restaurants: [
            {
                name: "락사마나",
                emoji: "🍛",
                type: "인도네시아 요리",
                price: "$$$",
            },
            { name: "징바란 씨푸드", emoji: "🦞", type: "해산물", price: "$$" },
            { name: "누리스 워룽", emoji: "🥘", type: "발리 전통", price: "$" },
        ],
        hotels: [
            { name: "포시즌스 리조트", rating: "⭐⭐⭐⭐⭐", area: "짐바란" },
            { name: "우붓 빌라", rating: "⭐⭐⭐⭐", area: "우붓" },
        ],
        tips: [
            "💵 현금 준비 (시골 지역)",
            "🏍️ 오토바이 렌트 추천",
            "☀️ 자외선 차단제 필수",
            "🙏 사원 방문시 사롱 착용",
        ],
    },
    뉴욕: {
        bestSeason: "봄(4-6월), 가을(9-11월)",
        weather: "냉대습윤기후, 4계절 뚜렷",
        currency: "미국 달러(USD)",
        language: "영어",
        timezone: "GMT-5",
        attractions: [
            { name: "자유의 여신상", emoji: "🗽", description: "미국의 상징" },
            { name: "타임스퀘어", emoji: "🌃", description: "세계의 중심" },
            { name: "센트럴 파크", emoji: "🌳", description: "도심 속 공원" },
            {
                name: "브루클린 브릿지",
                emoji: "🌉",
                description: "역사적 다리",
            },
        ],
        restaurants: [
            { name: "쉐이크쉑", emoji: "🍔", type: "버거", price: "$$" },
            { name: "케이츠 델리", emoji: "🥪", type: "델리", price: "$$$" },
            { name: "피터 루거", emoji: "🥩", type: "스테이크", price: "$$$$" },
        ],
        hotels: [
            { name: "더 플라자", rating: "⭐⭐⭐⭐⭐", area: "센트럴 파크" },
            { name: "1 호텔 브루클린", rating: "⭐⭐⭐⭐", area: "브루클린" },
        ],
        tips: [
            "🚇 메트로카드 구매 필수",
            "💰 팁 문화 (15-20%)",
            "🎭 브로드웨이 사전 예약",
            "🗽 관광지 사전 티켓 구매",
        ],
    },
    오사카: {
        bestSeason: "봄(3-5월), 가을(9-11월)",
        weather: "온대기후, 여름 덥고 습함",
        currency: "일본 엔(JPY)",
        language: "일본어",
        timezone: "GMT+9",
        attractions: [
            {
                name: "오사카성",
                emoji: "🏯",
                description: "일본 3대 성 중 하나",
            },
            { name: "도톤보리", emoji: "🎪", description: "네온사인 거리" },
            { name: "유니버설 스튜디오", emoji: "🎢", description: "테마파크" },
            {
                name: "우메다 스카이빌딩",
                emoji: "🏙️",
                description: "공중정원 전망대",
            },
        ],
        restaurants: [
            { name: "다이타", emoji: "🥟", type: "타코야키", price: "¥" },
            {
                name: "쿠시카츠 다루마",
                emoji: "🍢",
                type: "꼬치튀김",
                price: "¥¥",
            },
            { name: "이치란", emoji: "🍜", type: "라멘", price: "¥" },
        ],
        hotels: [
            {
                name: "세인트 레지스 오사카",
                rating: "⭐⭐⭐⭐⭐",
                area: "미도스지",
            },
            { name: "크로스 호텔", rating: "⭐⭐⭐⭐", area: "난바" },
        ],
        tips: [
            "🎫 JR 패스 구매 고려",
            "🍜 도톤보리 먹거리 투어",
            "🎢 USJ 사전 티켓 구매",
            "🛍️ 면세점 이용",
        ],
    },
    런던: {
        bestSeason: "여름(6-8월), 가을(9-10월)",
        weather: "해양성기후, 비 자주 옴",
        currency: "영국 파운드(GBP)",
        language: "영어",
        timezone: "GMT+0",
        attractions: [
            { name: "빅벤", emoji: "🕰️", description: "��던의 상징" },
            {
                name: "대영박물관",
                emoji: "🏛️",
                description: "세계 최대 박물관",
            },
            { name: "타워 브릿지", emoji: "🌉", description: "도개교" },
            { name: "버킹엄 궁전", emoji: "👑", description: "영국 왕실" },
        ],
        restaurants: [
            { name: "디쉬럼", emoji: "🍛", type: "인도 요리", price: "££" },
            { name: "보로우 마켓", emoji: "🥖", type: "푸드마켓", price: "££" },
            { name: "스케치", emoji: "☕", type: "애프터눈 티", price: "£££" },
        ],
        hotels: [
            { name: "더 사보이", rating: "⭐⭐⭐⭐⭐", area: "웨스트민스터" },
            { name: "시티즌엠", rating: "⭐⭐⭐", area: "뱅크사이드" },
        ],
        tips: [
            "🎫 오이스터 카드 필수",
            "☔ 우산 항상 휴대",
            "🎭 웨스트엔드 뮤지컬 사전 예약",
            "🏛️ 주요 박물관 무료 입장",
        ],
    },
    싱가포르: {
        bestSeason: "연중(건기 2-4월)",
        weather: "열대기후, 연중 고온다습",
        currency: "싱가포르 달러(SGD)",
        language: "영어, 중국어, 말레이어",
        timezone: "GMT+8",
        attractions: [
            {
                name: "마리나 베이 샌즈",
                emoji: "🏨",
                description: "싱가포르의 랜드마크",
            },
            {
                name: "가든스 바이 더 베이",
                emoji: "🌳",
                description: "미래형 식물원",
            },
            { name: "센토사", emoji: "🎢", description: "종합 리조트 섬" },
            {
                name: "머라이언 파크",
                emoji: "🦁",
                description: "싱가포르 상징",
            },
        ],
        restaurants: [
            { name: "호커센터", emoji: "🍜", type: "현지 음식", price: "$$" },
            {
                name: "점보 씨푸드",
                emoji: "🦀",
                type: "칠리크랩",
                price: "$$$",
            },
            { name: "송파 바쿠테", emoji: "🍲", type: "바쿠테", price: "$$" },
        ],
        hotels: [
            {
                name: "마리나 베이 샌즈",
                rating: "⭐⭐⭐⭐⭐",
                area: "마리나 베이",
            },
            { name: "래플즈 호텔", rating: "⭐⭐⭐⭐⭐", area: "시티홀" },
        ],
        tips: [
            "🚇 EZ-Link 카드 구매",
            "🍃 실내는 춥고 밖은 더움",
            "🚭 금연 구역 엄격",
            "💰 현금보다 카드 편리",
        ],
    },
    두바이: {
        bestSeason: "겨울(11-3월)",
        weather: "사막기후, 여름 매우 더움",
        currency: "UAE 디르함(AED)",
        language: "아랍어, 영어",
        timezone: "GMT+4",
        attractions: [
            {
                name: "부르즈 칼리파",
                emoji: "🏙️",
                description: "세계에서 가장 높�� 빌딩",
            },
            { name: "두바이 몰", emoji: "🛍️", description: "세계 최대 쇼핑몰" },
            { name: "사막 사파리", emoji: "🐪", description: "사막 액티비티" },
            { name: "팜 주메이라", emoji: "🏝️", description: "인공 섬" },
        ],
        restaurants: [
            {
                name: "앳모스피어",
                emoji: "🍽️",
                type: "파인다이닝",
                price: "$$$$",
            },
            { name: "알 말라", emoji: "🥙", type: "중동 요리", price: "$$" },
            { name: "피어 슈", emoji: "🍤", type: "씨푸드", price: "$$$" },
        ],
        hotels: [
            {
                name: "버즈 알 아랍",
                rating: "⭐⭐⭐⭐⭐⭐⭐",
                area: "주메이라",
            },
            {
                name: "아틀란티스 더 팜",
                rating: "⭐⭐⭐⭐⭐",
                area: "팜 주메이라",
            },
        ],
        tips: [
            "👗 보수적인 복장 권장",
            "🚇 메트로 편리하고 저렴",
            "💳 팁 문화 없음",
            "🌡️ 여름은 피하세요",
        ],
    },
    바르셀로나: {
        bestSeason: "봄(4-6월), 가을(9-10월)",
        weather: "지��해성기후, 온화",
        currency: "유로(EUR)",
        language: "카탈루냐어, 스페인어",
        timezone: "GMT+1",
        attractions: [
            {
                name: "사그라다 파밀리아",
                emoji: "⛪",
                description: "가우디의 미완성 걸작",
            },
            { name: "구엘 공원", emoji: "🏞️", description: "가우디의 공원" },
            {
                name: "람블라스 거리",
                emoji: "🚶",
                description: "활기찬 산책로",
            },
            { name: "카사 밀라", emoji: "🏛️", description: "가우디 건축물" },
        ],
        restaurants: [
            {
                name: "세르베세리아 카탈라나",
                emoji: "🍤",
                type: "타파스",
                price: "€€",
            },
            { name: "7 포르테스", emoji: "🥘", type: "파에야", price: "€€€" },
            { name: "보케리아 시장", emoji: "🍊", type: "시장", price: "€" },
        ],
        hotels: [
            { name: "호텔 아츠", rating: "⭐⭐⭐⭐⭐", area: "바르셀로네타" },
            { name: "카사 피스터", rating: "⭐⭐⭐⭐", area: "고딕 지구" },
        ],
        tips: [
            "🎫 사그라다 사전 예약 필수",
            "👜 소매치기 주의",
            "🕐 시에스타 시간 고려",
            "🎭 플라멩코 공연 관람",
        ],
    },
    시드니: {
        bestSeason: "봄(9-11월), 가을(3-5월)",
        weather: "온대기후, 사계절 뚜렷",
        currency: "호주 달러(AUD)",
        language: "영어",
        timezone: "GMT+10",
        attractions: [
            {
                name: "오페라 하우스",
                emoji: "🎭",
                description: "시드니의 상징",
            },
            { name: "하버 브릿지", emoji: "🌉", description: "아름다운 다리" },
            { name: "본다이 비치", emoji: "🏖️", description: "유명한 해변" },
            { name: "블루 마운틴", emoji: "⛰️", description: "자연 경관" },
        ],
        restaurants: [
            { name: "퀘이", emoji: "🍽️", type: "파인다이닝", price: "$$$$" },
            { name: "피쉬 마켓", emoji: "🐟", type: "해산물", price: "$$" },
            { name: "차이나타운", emoji: "🥟", type: "중식", price: "$" },
        ],
        hotels: [
            { name: "파크 하얏트", rating: "⭐⭐⭐⭐⭐", area: "서큘러 키" },
            { name: "샹그릴라", rating: "⭐⭐⭐⭐⭐", area: "록스" },
        ],
        tips: [
            "☀️ 자외선 차단제 필수",
            "🚌 오팔 카드 구매",
            "🦘 와일드라이프 투어",
            "🍷 와이너리 투어 추천",
        ],
    },
    로마: {
        bestSeason: "봄(4-6월), 가을(9-10월)",
        weather: "지중해성기후, 여름 더움",
        currency: "유로(EUR)",
        language: "이탈리아어",
        timezone: "GMT+1",
        attractions: [
            {
                name: "콜로세움",
                emoji: "🏛️",
                description: "고대 로마 원형경기장",
            },
            { name: "바티칸 시국", emoji: "⛪", description: "교황청" },
            { name: "트레비 분수", emoji: "⛲", description: "소원의 분수" },
            { name: "판테온", emoji: "🏰", description: "고대 신전" },
        ],
        restaurants: [
            { name: "다 엔초", emoji: "🍝", type: "파스타", price: "€€" },
            { name: "피자리움", emoji: "🍕", type: "피자", price: "€" },
            { name: "젤라테리아", emoji: "🍦", type: "젤라또", price: "€" },
        ],
        hotels: [
            { name: "호텔 드 루시", rating: "⭐⭐⭐⭐⭐", area: "스페인 광장" },
            { name: "캄포 데 피오리", rating: "⭐⭐⭐⭐", area: "센트로" },
        ],
        tips: [
            "🎫 주요 명소 사전 예약",
            "👗 바티칸 복장 규정",
            "💰 현금 준비",
            "🕐 시에스타 시간 고려",
        ],
    },
    방콕: {
        bestSeason: "건기(11-2월)",
        weather: "열대기후, 연중 더움",
        currency: "태국 바트(THB)",
        language: "태국어",
        timezone: "GMT+7",
        attractions: [
            { name: "왕궁", emoji: "👑", description: "태국 왕실 궁전" },
            { name: "왓 아룬", emoji: "⛩️", description: "새벽 사원" },
            { name: "왓 포", emoji: "🛕", description: "와불 사원" },
            {
                name: "카오산 로드",
                emoji: "🎉",
                description: "배낭여행자의 거리",
            },
        ],
        restaurants: [
            {
                name: "팟타이 팁 사마이",
                emoji: "🍜",
                type: "팟타이",
                price: "$",
            },
            { name: "솜분 씨푸드", emoji: "🦐", type: "해산물", price: "$$" },
            { name: "망고 탱고", emoji: "🥭", type: "디저트", price: "$" },
        ],
        hotels: [
            {
                name: "만다린 오리엔탈",
                rating: "⭐⭐⭐⭐⭐",
                area: "차오프라야 강변",
            },
            { name: "더 페닌슐라", rating: "⭐⭐⭐⭐⭐", area: "톤부리" },
        ],
        tips: [
            "🚕 그랩 앱 사용",
            "🙏 사원 복장 주의",
            "💵 현금 많이 준비",
            "🌶️ 매운 정도 조절 요청",
        ],
    },
};
